{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ghibli
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ghibli_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ghibli/ghibli_{{ version }}.tar.gz
  sha256: f985cfc44f8b622c898661d3efa167e341e6b1da7bdc13f0c130c1f5b46745e2

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-prismatic
  run:
    - r-base
    - r-prismatic

test:
  commands:
    - $R -e "library('ghibli')"           # [not win]
    - "\"%R%\" -e \"library('ghibli')\""  # [win]

about:
  home: https://ewenme.github.io/ghibli/, https://github.com/ewenme/ghibli
  license: MIT
  summary: Colour palettes inspired by Studio Ghibli <https://en.wikipedia.org/wiki/Studio_Ghibli> films, ported to R for your enjoyment.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
